# Generated by Django 5.2.4 on 2025-12-19 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=100)),
                ("pub_year", models.IntegerField(blank=True, null=True)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("loan_count", models.IntegerField(default=0)),
                (
                    "owned_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owned_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wish_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wish_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
