# Generated by Django 5.2.4 on 2025-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_alter_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('lib_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lib_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
