# Generated by Django 5.2.4 on 2025-12-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_tradechatroom_trademessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('LIBRARY_STORED', '도서관 보관 중'), ('COMPLETED', '거래 완료')], max_length=20)),
                ('request_status', models.CharField(choices=[('PENDING', '대기 중'), ('ACCEPTED', '수락됨'), ('REJECTED', '거절됨')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_requests', to='community.tradechatroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'new_status')},
            },
        ),
    ]
