# Generated by Django 5.2.4 on 2025-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_tradestatusrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradechatroom',
            name='status',
            field=models.CharField(choices=[('REQUESTED', '거래 요청'), ('APPROVED', '거래 승인'), ('LIBRARY_STORED', '도서관 보관 중'), ('COMPLETED', '거래 완료')], default='REQUESTED', max_length=20),
        ),
    ]
