# Generated by Django 5.2.4 on 2025-12-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_tradechatroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradechatroom',
            name='location',
            field=models.CharField(blank=True, help_text='거래 장소', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradechatroom',
            name='locker_number',
            field=models.CharField(blank=True, help_text='도서 보관함 번호', max_length=50, null=True),
        ),
    ]
