# Generated by Django 5.2.4 on 2025-12-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_tradechatroom_location_tradechatroom_locker_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradechatroom",
            name="library_address",
            field=models.CharField(
                blank=True, help_text="도서관 상세 주소", max_length=255, null=True
            ),
        ),
    ]
