# Generated by Django 5.2.4 on 2025-12-21 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="favorite_libraries",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="최소 하나 이상의 도서관을 선택해야 합니다."
                    )
                ],
                verbose_name="자주 이용하는 공공도서관",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_genres",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="최소 하나 이상의 카테고리를 선택해야 합니다."
                    )
                ],
                verbose_name="선호 카테고리",
            ),
        ),
    ]
